name: golangci-lint-test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18", "1.19", "1.20", "1.21"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  golangci-test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18", "1.19", "1.20", "1.21"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: test
        run: go test -C pkg
